# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  DOMAIN_NAME: "https://198c6db2.ngrok.io"
  ID_CLIENT_EMT: "WEB.SERV.ignaciomorenopubul@gmail.com"
  PASSKEY_EMT: "20A8A37A-5D64-4EF7-9D79-B8F85CCD9EA6"
  GEOCODING_API: "AIzaSyDaeQwIQMQZn3N85_mE7wvp6HQpny8_UIM"
  PAGE_ACCESS_TOKEN: "EAAFA9zfdT70BAPjWvFJ8EuswV3sWRa1XqehI7InXsxXNx8Ujfrhq7C7lR911jaMWPpOUqToIiZBjtwPHDNgfoi10Kn19uFsJHbtwBAdyNtK7WCfi4Axb7hCBZC0RIcnyfwWtcahnfxkQk48deqSKiGHkNi0DWkirKgLawj7AZDZD"
  APP_SECRET: "15ec26de8b321134de109504db1c17fd"
  VERIFY_TOKEN: "github"
  API_AI_TOKEN: "e2c5025b413c4a56a38cf5a138795293"


  

production:
  DOMAIN_NAME: "https://kittybus-madrid.herokuapp.com/"
  ID_CLIENT_EMT: "WEB.SERV.ignaciomorenopubul@gmail.com"
  PASSKEY_EMT: "20A8A37A-5D64-4EF7-9D79-B8F85CCD9EA6"
  GEOCODING_API: "AIzaSyDaeQwIQMQZn3N85_mE7wvp6HQpny8_UIM"
  PAGE_ACCESS_TOKEN: "EAAEAdXZBdERwBAD6k8nfpDcbeRriupKHSV7X69mvJMWnsutfGZBVmUy8L7f5EUx5xQlz1e02iZAnMP3JfaMBoQtwlEr09b0QgCHzZCX5s4A0r7ww0nkeRugZBJXkl7ZCfwMBbQXZCHkAZBJb6KVmeLgBRQL9GH3KQh6ZCIgwK38JezAZDZD"
  APP_SECRET: "e84ca2ceb1e149a07d51c5af254aa357"
  VERIFY_TOKEN: "github"
  API_AI_TOKEN: "c751f5352ae54721b534db32ca7b8c3e"